VISI KOMPUTER DAN PENGOLAHAN CITRA

UTS NO.3 KONVOLUSI GAMBAR

In [1]:
import numpy as np

# Example image and kernel
imageX = np.array([[1, 0, 0, 0],
                  [1, 1, 1, 0],
                  [1, 1, 1, 0],
                  [1, 0, 0, 0]])
print("Input Gambar X:\n",imageX)
kernelH = np.array([[1, 1, 1],
                   [1, 4, 1],
                   [1, 1, 1]])
print("Input Kernel H:\n",kernelH)

# Coordinates for the point (2, 3)
i, j = 2, 3

# Calculate convolution at (2, 3)
convolution_result = np.sum(np.sum(kernelH * imageX[i-2:i+1, j-2:j+1]))

print(f"Hasil Konvolusi Y({i}, {j}): {convolution_result}")

Input Gambar X:
 [[1 0 0 0]
 [1 1 1 0]
 [1 1 1 0]
 [1 0 0 0]]
Input Kernel H:
 [[1 1 1]
 [1 4 1]
 [1 1 1]]
Hasil Konvolusi Y(2, 3): 7
